### PR TITLE
Added find_all and replace_all commands and respective tests

### PR DESCRIPTION
**Pull request by datNurd**
Added functions to replace all occurrences of a search text, as well as find all occurrences of a search text.

Solved the issue referred in #19

### CODE REVIEW

**Comment by datNurd** [comment]
Hi can someone tell me what exactly happened? what caused the tests to fail, is it due to my part of the commit or some other code? locally all the tests passed.

Note: Building on a windows 10 system

**Comment by zoli** [comment]
> Hi can someone tell me what exactly happened?

Hi, The check_fmt command did not pass on your code. Which it means your go code is not fmted(check [here](https://blog.golang.org/go-fmt-your-code) if you want to know more about go fmt tool). Also you can use the make file and run `make fmt` to fix it.

Other than the fmt problem every thing seems ok to me.

**Comment by datNurd** [comment]
One of the builds is stalling in Travis.

**Comment by zoli** [comment]
LGTM, Thanks.

**Pull request merged**
